version: "3"
services:
  postgres:
    image: postgres:14.9-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jwt
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  jwt-example:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: jwt-example
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jwt
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - postgres