server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost/jwt
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

jwt:
  token:
    secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
    expired: 3600000